# Generated by Django 5.1.4 on 2024-12-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=15)),
                ('next_of_kin', models.CharField(max_length=100)),
                ('next_of_kin_phone_number', models.CharField(max_length=15)),
                ('dnr_status', models.BooleanField(default=False)),
                ('nfc_tag_available', models.BooleanField(default=False)),
            ],
        ),
    ]
